# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 266)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.config_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.config_tabs.setObjectName("config_tabs")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.file_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.file_scroll = QtWidgets.QScrollArea(self.file_tab)
        self.file_scroll.setWidgetResizable(True)
        self.file_scroll.setObjectName("file_scroll")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 569, 131))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.directory_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory_line_edit.sizePolicy().hasHeightForWidth())
        self.directory_line_edit.setSizePolicy(sizePolicy)
        self.directory_line_edit.setObjectName("directory_line_edit")
        self.gridLayout_7.addWidget(self.directory_line_edit, 0, 1, 1, 1)
        self.directory_push_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory_push_button.sizePolicy().hasHeightForWidth())
        self.directory_push_button.setSizePolicy(sizePolicy)
        self.directory_push_button.setObjectName("directory_push_button")
        self.gridLayout_7.addWidget(self.directory_push_button, 0, 2, 1, 1)
        self.directory_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.directory_label.setObjectName("directory_label")
        self.gridLayout_7.addWidget(self.directory_label, 0, 0, 1, 1)
        self.queue_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.queue_label.setObjectName("queue_label")
        self.gridLayout_7.addWidget(self.queue_label, 1, 0, 1, 1)
        self.enqueue_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.enqueue_label.setObjectName("enqueue_label")
        self.gridLayout_7.addWidget(self.enqueue_label, 2, 0, 1, 1)
        self.queue_dropdown = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queue_dropdown.sizePolicy().hasHeightForWidth())
        self.queue_dropdown.setSizePolicy(sizePolicy)
        self.queue_dropdown.setObjectName("queue_dropdown")
        self.queue_dropdown.addItem("")
        self.queue_dropdown.addItem("")
        self.gridLayout_7.addWidget(self.queue_dropdown, 1, 1, 1, 2)
        self.enqueue_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enqueue_checkbox.sizePolicy().hasHeightForWidth())
        self.enqueue_checkbox.setSizePolicy(sizePolicy)
        self.enqueue_checkbox.setText("")
        self.enqueue_checkbox.setObjectName("enqueue_checkbox")
        self.gridLayout_7.addWidget(self.enqueue_checkbox, 2, 1, 1, 2)
        self.gridLayout_7.setColumnStretch(0, 2)
        self.gridLayout_7.setColumnStretch(1, 4)
        self.gridLayout_7.setColumnStretch(2, 1)
        self.file_scroll.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_5.addWidget(self.file_scroll, 0, 1, 1, 1)
        self.config_tabs.addTab(self.file_tab, "")
        self.images_tab = QtWidgets.QWidget()
        self.images_tab.setObjectName("images_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.images_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.images_scroll = QtWidgets.QScrollArea(self.images_tab)
        self.images_scroll.setWidgetResizable(True)
        self.images_scroll.setObjectName("images_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 569, 131))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.format_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_label.sizePolicy().hasHeightForWidth())
        self.format_label.setSizePolicy(sizePolicy)
        self.format_label.setObjectName("format_label")
        self.gridLayout_10.addWidget(self.format_label, 0, 0, 1, 1)
        self.scaling_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.scaling_line_edit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaling_line_edit.sizePolicy().hasHeightForWidth())
        self.scaling_line_edit.setSizePolicy(sizePolicy)
        self.scaling_line_edit.setObjectName("scaling_line_edit")
        self.gridLayout_10.addWidget(self.scaling_line_edit, 2, 1, 1, 1)
        self.format_dropdown = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_dropdown.sizePolicy().hasHeightForWidth())
        self.format_dropdown.setSizePolicy(sizePolicy)
        self.format_dropdown.setObjectName("format_dropdown")
        self.format_dropdown.addItem("")
        self.format_dropdown.addItem("")
        self.gridLayout_10.addWidget(self.format_dropdown, 0, 1, 1, 1)
        self.whitepoint_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.whitepoint_line_edit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whitepoint_line_edit.sizePolicy().hasHeightForWidth())
        self.whitepoint_line_edit.setSizePolicy(sizePolicy)
        self.whitepoint_line_edit.setObjectName("whitepoint_line_edit")
        self.gridLayout_10.addWidget(self.whitepoint_line_edit, 1, 1, 1, 1)
        self.scaling_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.scaling_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaling_label.sizePolicy().hasHeightForWidth())
        self.scaling_label.setSizePolicy(sizePolicy)
        self.scaling_label.setObjectName("scaling_label")
        self.gridLayout_10.addWidget(self.scaling_label, 2, 0, 1, 1)
        self.whitepoint_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.whitepoint_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whitepoint_label.sizePolicy().hasHeightForWidth())
        self.whitepoint_label.setSizePolicy(sizePolicy)
        self.whitepoint_label.setObjectName("whitepoint_label")
        self.gridLayout_10.addWidget(self.whitepoint_label, 1, 0, 1, 1)
        self.radius_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.radius_label.setObjectName("radius_label")
        self.gridLayout_10.addWidget(self.radius_label, 3, 0, 1, 1)
        self.radius_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radius_line_edit.sizePolicy().hasHeightForWidth())
        self.radius_line_edit.setSizePolicy(sizePolicy)
        self.radius_line_edit.setObjectName("radius_line_edit")
        self.gridLayout_10.addWidget(self.radius_line_edit, 3, 1, 1, 1)
        self.images_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.images_scroll, 0, 0, 1, 1)
        self.config_tabs.addTab(self.images_tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -81, 548, 275))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.norm_percentile_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.norm_percentile_label.setEnabled(False)
        self.norm_percentile_label.setObjectName("norm_percentile_label")
        self.gridLayout_9.addWidget(self.norm_percentile_label, 1, 0, 1, 1)
        self.norm_percentile_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.norm_percentile_line_edit.setEnabled(False)
        self.norm_percentile_line_edit.setObjectName("norm_percentile_line_edit")
        self.gridLayout_9.addWidget(self.norm_percentile_line_edit, 1, 1, 1, 1)
        self.masking_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.masking_label.setObjectName("masking_label")
        self.gridLayout_9.addWidget(self.masking_label, 2, 0, 1, 1)
        self.masking_dropdown = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.masking_dropdown.setObjectName("masking_dropdown")
        self.masking_dropdown.addItem("")
        self.masking_dropdown.addItem("")
        self.gridLayout_9.addWidget(self.masking_dropdown, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 8, 0, 1, 2)
        self.required_stable_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.required_stable_line_edit.setObjectName("required_stable_line_edit")
        self.gridLayout_9.addWidget(self.required_stable_line_edit, 10, 1, 1, 1)
        self.extraction_dropdown = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.extraction_dropdown.setObjectName("extraction_dropdown")
        self.extraction_dropdown.addItem("")
        self.extraction_dropdown.addItem("")
        self.gridLayout_9.addWidget(self.extraction_dropdown, 7, 1, 1, 1)
        self.required_stable_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.required_stable_label.setObjectName("required_stable_label")
        self.gridLayout_9.addWidget(self.required_stable_label, 10, 0, 1, 1)
        self.extraction_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.extraction_label.setObjectName("extraction_label")
        self.gridLayout_9.addWidget(self.extraction_label, 7, 0, 1, 1)
        self.maximum_checks_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.maximum_checks_label.setObjectName("maximum_checks_label")
        self.gridLayout_9.addWidget(self.maximum_checks_label, 12, 0, 1, 1)
        self.normalization_checkbox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.normalization_checkbox.setText("")
        self.normalization_checkbox.setObjectName("normalization_checkbox")
        self.gridLayout_9.addWidget(self.normalization_checkbox, 0, 1, 1, 1)
        self.check_delay_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.check_delay_label.setObjectName("check_delay_label")
        self.gridLayout_9.addWidget(self.check_delay_label, 11, 0, 1, 1)
        self.max_checks_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.max_checks_line_edit.setObjectName("max_checks_line_edit")
        self.gridLayout_9.addWidget(self.max_checks_line_edit, 12, 1, 1, 1)
        self.check_delay_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.check_delay_line_edit.setObjectName("check_delay_line_edit")
        self.gridLayout_9.addWidget(self.check_delay_line_edit, 11, 1, 1, 1)
        self.normalization_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.normalization_label.setObjectName("normalization_label")
        self.gridLayout_9.addWidget(self.normalization_label, 0, 0, 1, 1)
        self.thresh_intensity_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.thresh_intensity_label.setEnabled(False)
        self.thresh_intensity_label.setObjectName("thresh_intensity_label")
        self.gridLayout_9.addWidget(self.thresh_intensity_label, 3, 0, 1, 1)
        self.thresh_intensity_line_edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.thresh_intensity_line_edit.setEnabled(False)
        self.thresh_intensity_line_edit.setObjectName("thresh_intensity_line_edit")
        self.gridLayout_9.addWidget(self.thresh_intensity_line_edit, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 9, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.config_tabs.addTab(self.tab_5, "")
        self.gridLayout_4.addWidget(self.config_tabs, 0, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setEnabled(False)
        self.save_button.setObjectName("save_button")
        self.gridLayout_4.addWidget(self.save_button, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.config_tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.directory_push_button.setText(_translate("MainWindow", "Select"))
        self.directory_label.setText(_translate("MainWindow", "Directory"))
        self.queue_label.setText(_translate("MainWindow", "Queue Type"))
        self.enqueue_label.setText(_translate("MainWindow", "Enqueue Existing Files In Directory?"))
        self.queue_dropdown.setItemText(0, _translate("MainWindow", "File (Lazy Loading)"))
        self.queue_dropdown.setItemText(1, _translate("MainWindow", "Image (Eager Loading)"))
        self.config_tabs.setTabText(self.config_tabs.indexOf(self.file_tab), _translate("MainWindow", "Files"))
        self.format_label.setText(_translate("MainWindow", "Image Format"))
        self.format_dropdown.setItemText(0, _translate("MainWindow", ".czi"))
        self.format_dropdown.setItemText(1, _translate("MainWindow", ".tiff"))
        self.scaling_label.setText(_translate("MainWindow", "Image Scaling (pixels/µm)"))
        self.whitepoint_label.setText(_translate("MainWindow", "Image White Point"))
        self.radius_label.setText(_translate("MainWindow", "Maximum ROI Radius (pixels)"))
        self.config_tabs.setTabText(self.config_tabs.indexOf(self.images_tab), _translate("MainWindow", "Images"))
        self.norm_percentile_label.setText(_translate("MainWindow", "Normalization Percentile"))
        self.masking_label.setText(_translate("MainWindow", "Masking Method"))
        self.masking_dropdown.setItemText(0, _translate("MainWindow", "Thresholding (Faster)"))
        self.masking_dropdown.setItemText(1, _translate("MainWindow", "K-Means (Slower)"))
        self.extraction_dropdown.setItemText(0, _translate("MainWindow", "Contour"))
        self.extraction_dropdown.setItemText(1, _translate("MainWindow", "Eigenvalues"))
        self.required_stable_label.setText(_translate("MainWindow", "Successful Stability Checks Required Before Image Opened"))
        self.extraction_label.setText(_translate("MainWindow", "Circle Extraction Method"))
        self.maximum_checks_label.setText(_translate("MainWindow", "Maximum Stability Checks per Image"))
        self.check_delay_label.setText(_translate("MainWindow", "Delay Between Stability Checks"))
        self.normalization_label.setText(_translate("MainWindow", "Apply Normalization?"))
        self.thresh_intensity_label.setText(_translate("MainWindow", "Threshold Intensity"))
        self.config_tabs.setTabText(self.config_tabs.indexOf(self.tab_5), _translate("MainWindow", "Processing"))
        self.save_button.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
