# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'processing_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessingWindow(object):
    def setupUi(self, ProcessingWindow):
        ProcessingWindow.setObjectName("ProcessingWindow")
        ProcessingWindow.resize(430, 330)
        self.centralwidget = QtWidgets.QWidget(ProcessingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.output_textbox = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_textbox.setObjectName("output_textbox")
        self.gridLayout.addWidget(self.output_textbox, 0, 0, 1, 3)
        self.label_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.label_group_box.setEnabled(True)
        self.label_group_box.setObjectName("label_group_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.label_group_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_combo_box = QtWidgets.QComboBox(self.label_group_box)
        self.label_combo_box.setEditable(True)
        self.label_combo_box.setMaxVisibleItems(99)
        self.label_combo_box.setObjectName("label_combo_box")
        self.gridLayout_2.addWidget(self.label_combo_box, 0, 0, 1, 1)
        self.label_save_button = QtWidgets.QPushButton(self.label_group_box)
        self.label_save_button.setObjectName("label_save_button")
        self.gridLayout_2.addWidget(self.label_save_button, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.label_group_box, 1, 0, 1, 3)
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setObjectName("exit_button")
        self.gridLayout.addWidget(self.exit_button, 2, 2, 1, 1)
        ProcessingWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ProcessingWindow)
        self.statusbar.setObjectName("statusbar")
        ProcessingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProcessingWindow)
        QtCore.QMetaObject.connectSlotsByName(ProcessingWindow)

    def retranslateUi(self, ProcessingWindow):
        _translate = QtCore.QCoreApplication.translate
        ProcessingWindow.setWindowTitle(_translate("ProcessingWindow", "MainWindow"))
        self.label_group_box.setTitle(_translate("ProcessingWindow", "Label Image..."))
        self.label_save_button.setText(_translate("ProcessingWindow", "Add label to dropdown..."))
        self.exit_button.setText(_translate("ProcessingWindow", "Save and Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProcessingWindow = QtWidgets.QMainWindow()
    ui = Ui_ProcessingWindow()
    ui.setupUi(ProcessingWindow)
    ProcessingWindow.show()
    sys.exit(app.exec_())
